### ISSUE TITLE
ScrollTo

### ISSUE THREAD

**Issue by xstable** [experiment322/react-native-scrolling-menu#1]
Nice Fork of the scrolling-menu component. Does a better job then the original component.
Please could you add a property to ScrollMenu, so that you can use scrollTo() of <ScrollView> element?

Currently I've created two Icon beside the list, and on each click, the list should scroll by x pixel.

BTW: Even would be great If you could add the whole "chevron-right/left" functionality... but adding a way to access scrollTo (or scroll entry by entry to left/right) would fit my needs for now.

![image](https://user-images.githubusercontent.com/1778068/45950650-0a977b00-c001-11e8-833a-e82de64df6ea.png)

**Comment by experiment322** [comment]
Sorry for late reply, but couldn't you use a ref to access the method scrollTo?
It is undocumented, but if you look at the source code you'll find it.

Something like this should do (didn't test it):
```javascript
import React from 'react';
import ScrollingMenu from 'react-native-scrolling-menu';

const items = ['Menu Item 1','Menu Item 2','Menu Item 3','Menu Item 4','Menu Item 5'];

class Example extends React.Component {
    constructor(props) {
        super(props);
        this.menuRef = React.createRef(); // create the ref
    }

    componentDidMount() {
        // 'current' represents the component instance
        // scroll to the fifth element after one second
        setTimeout(() => this.menuRef.current.scrollTo(4), 1000);
    }

    render() {
        return (
          <ScrollingMenu
            ref={this.menuRef} // link the ref with the menu
            items={items}
            onSelect={(index) => {console.log(items[index]);}}
          />
        );
    } 
}
```
